name: ${project.name}
version: "${project.version}"
main: com.bencodez.aylachat.AylaChatMain
description: Highly Customizable Chat Plugin
author: BenCodez
api-version: 1.13
libraries:
  - org.openjdk.nashorn:nashorn-core:15.3
commands:
  aylachat:
    description: AylaChat Command
    aliases:
    - aylac
    - ach
  Msg:
    description: Msg another player
    aliases:
    - message
    - tell
  reply:
    description: Msg another player
    aliases:
    - r
  socialspy:
    description: Social spy
  clearchat:
    description: Clear chat
    aliases:
    - cc
  mute:
    description: Mute commands